# analysis_options.yaml

# Base set of recommended lints from the Dart team
include: package:lints/recommended.yaml

analyzer:
  # Exclude generated code and examples from analysis
  exclude:
    - "**/*.g.dart"
    - "example/**"

linter:
  rules:
    # Don’t leave debug prints in production code
    - avoid_print

    # Prefer const where possible
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables

    # Encourage immutability
    - prefer_final_locals

    # Style rules
    - annotate_overrides          # always annotate overridden members
    - avoid_return_types_on_setters
