name: dukascopy
description: A Dart wrapper for fetching data from Dukascopy Bank SA API.
version: 0.1.1
repository: https://github.com/Erhabor-Fona/dukascopy
homepage: https://github.com/Erhabor-Fona/dukascopy

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  http: ^1.2.1
  intl: ^0.19.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
